"""empty message

Revision ID: 1c1671ea20ee
Revises: 4624ac6f94a1
Create Date: 2025-04-05 10:19:09.173010

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1c1671ea20ee"
down_revision: Union[str, None] = "4624ac6f94a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "version_histories", sa.Column("current_version", sa.Boolean(), nullable=True)
    )
    op.drop_column("version_histories", "version")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "version_histories",
        sa.Column("version", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("version_histories", "current_version")
    # ### end Alembic commands ###
