"""empty message

Revision ID: 20746f4a5a4d
Revises: 6546070f4ade
Create Date: 2025-03-23 16:15:29.244400

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20746f4a5a4d"
down_revision: Union[str, None] = "6546070f4ade"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "categories", ["title"])
    op.create_unique_constraint(None, "sub_categories", ["title"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sub_categories", type_="unique")
    op.drop_constraint(None, "categories", type_="unique")
    # ### end Alembic commands ###
