"""empty message

Revision ID: 401dbf16370d
Revises: c81d7085d784
Create Date: 2025-04-06 14:08:03.651741

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "401dbf16370d"
down_revision: Union[str, None] = "c81d7085d784"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document_comments", sa.Column("user_id", sa.Integer(), nullable=False)
    )
    op.drop_constraint(
        "document_comments_created_by_fkey", "document_comments", type_="foreignkey"
    )
    op.create_foreign_key(None, "document_comments", "users", ["user_id"], ["id"])
    op.drop_column("document_comments", "created_by")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document_comments",
        sa.Column("created_by", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "document_comments", type_="foreignkey")
    op.create_foreign_key(
        "document_comments_created_by_fkey",
        "document_comments",
        "users",
        ["created_by"],
        ["id"],
    )
    op.drop_column("document_comments", "user_id")
    # ### end Alembic commands ###
