"""empty message

Revision ID: 43c012d594af
Revises: 7f3ec8caf65b
Create Date: 2025-04-05 12:41:31.403905

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "43c012d594af"
down_revision: Union[str, None] = "7f3ec8caf65b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "document_histories", "document_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "version_histories", "document_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "version_histories", "document_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "document_histories", "document_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
