"""empty message

Revision ID: 44ec6716fef1
Revises: 43c012d594af
Create Date: 2025-04-05 12:46:09.256413

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "44ec6716fef1"
down_revision: Union[str, None] = "43c012d594af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "version_histories_document_id_fkey", "version_histories", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "version_histories",
        "documents",
        ["document_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "version_histories", type_="foreignkey")
    op.create_foreign_key(
        "version_histories_document_id_fkey",
        "version_histories",
        "documents",
        ["document_id"],
        ["id"],
    )
    # ### end Alembic commands ###
