"""empty message

Revision ID: 6546070f4ade
Revises: d66ab022b3e0
Create Date: 2025-03-23 12:27:22.721868

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6546070f4ade"
down_revision: Union[str, None] = "d66ab022b3e0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_admin", sa.Boolean(), nullable=False))
    op.drop_column("users", "is_owner")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("is_owner", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("users", "is_admin")
    # ### end Alembic commands ###
