"""empty message

Revision ID: 70c1c30b23f2
Revises: 91c2acebe74a
Create Date: 2025-04-05 12:47:19.533848

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "70c1c30b23f2"
down_revision: Union[str, None] = "91c2acebe74a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
