"""empty message

Revision ID: 7638bd5d57e4
Revises: 401dbf16370d
Create Date: 2025-04-24 10:21:24.512946

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7638bd5d57e4"
down_revision: Union[str, None] = "401dbf16370d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "roles_permissions_role_id_fkey", "roles_permissions", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "roles_permissions", "roles", ["role_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "roles_permissions", type_="foreignkey")
    op.create_foreign_key(
        "roles_permissions_role_id_fkey",
        "roles_permissions",
        "roles",
        ["role_id"],
        ["id"],
    )
    # ### end Alembic commands ###
