"""empty message

Revision ID: 91c2acebe74a
Revises: 44ec6716fef1
Create Date: 2025-04-05 12:46:35.403997

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "91c2acebe74a"
down_revision: Union[str, None] = "44ec6716fef1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "document_histories_document_id_fkey", "document_histories", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "document_histories",
        "documents",
        ["document_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "document_histories", type_="foreignkey")
    op.create_foreign_key(
        "document_histories_document_id_fkey",
        "document_histories",
        "documents",
        ["document_id"],
        ["id"],
    )
    # ### end Alembic commands ###
