"""empty message

Revision ID: ae7f1f18ff54
Revises: ca19eafb91d3
Create Date: 2025-04-06 12:19:47.786187

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ae7f1f18ff54"
down_revision: Union[str, None] = "ca19eafb91d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("categories", "parent_id")
    op.drop_column("documents", "parent_id")
    op.drop_column("sub_categories", "parent_id")
    op.drop_column("tags", "parent_id")
    op.drop_column("users", "parent_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("parent_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "tags", sa.Column("parent_id", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "sub_categories",
        sa.Column("parent_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "documents",
        sa.Column("parent_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "categories",
        sa.Column("parent_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
