"""empty message

Revision ID: ca19eafb91d3
Revises: 70c1c30b23f2
Create Date: 2025-04-05 12:54:53.104677

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ca19eafb91d3"
down_revision: Union[str, None] = "70c1c30b23f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "version_histories", sa.Column("document_name", sa.String(), nullable=True)
    )
    op.drop_column("version_histories", "file_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "version_histories",
        sa.Column("file_name", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("version_histories", "document_name")
    # ### end Alembic commands ###
